### ISSUE TITLE
Fatal error template file: template repositories.html can't be loaded

### ISSUE THREAD

**Issue by fti-sfuke** [Quiq/docker-registry-ui#69]
```
root@DEB-NUC10i5F-G6FN04300231:~/samadhan/scorer/Manufacturing/debian/scripts# docker logs scorer_registry_ui 
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.1.16
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:9010
echo: http: panic serving 127.0.0.1:41048: Fatal error template file: template repositories.html can't be loaded
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc00038a000)
        /usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x9c3e00, 0xc00005e070)
        /usr/local/go/src/runtime/panic.go:971 +0x499
main.(*Template).Render(0xc00041a008, 0xafd940, 0xc000380270, 0xa5b32d, 0x11, 0x9fa600, 0xc000380240, 0xb0e148, 0xc00038a0a0, 0xc00012a6c0, ...)
        /opt/src/template.go:24 +0x254
github.com/labstack/echo/v4.(*context).Render(0xc00038a0a0, 0xc8, 0xa5b32d, 0x11, 0x9fa600, 0xc000380240, 0x1, 0x0)
        /root/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/context.go:417 +0xc9
main.(*apiClient).viewRepositories(0xc000110100, 0xb0e148, 0xc00038a0a0, 0xc0003801e0, 0xc000057b08)
        /opt/src/main.go:186 +0x2bd
github.com/labstack/echo/v4.(*Echo).add.func1(0xb0e148, 0xc00038a0a0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:512 +0x8f
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000428000, 0xb05e80, 0xc000392000, 0xc00038e000)

```

**Comment by roman-vynar** [comment]
Once compiled you are still required to provide static files along with the binary.
